# services définit les services à lancer
# db: service de base de données MySQL
# app: service de l'application Spring Boot
# volumes: définit les volumes à monter
# networks: définit les réseaux à utiliser
services:
  db:
    image: mysql:8.2.0
    container_name: chatop-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/docker/init:/docker-entrypoint-initdb.d/
    networks:
      - chatop-network # Réseau à utiliser
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  vault:
    image: hashicorp/vault
    container_name: chatop-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: "http://127.0.0.1:8200" 
    cap_add:
      - IPC_LOCK # Ajout de la capacité IPC_LOCK pour Vault ce qui permet de verrouiller la mémoire
    networks:
      - chatop-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      retries: 5
      start_period: 20s


  vault-init:
    image: vault:1.13.3
    container_name: chatop-vault-init
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ./vault-init.sh:/vault-init.sh
    command: /vault-init.sh
    networks:
      - chatop-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatop-app
    depends_on:
      db:
        condition: service_healthy
      vault-init:
        condition: service_completed_successfully
    environment:
      SPRING_PROFILES_ACTIVE: vault
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      SPRING_CLOUD_VAULT_SCHEME: http
      SPRING_CLOUD_VAULT_HOST: vault
      SPRING_CLOUD_VAULT_PORT: 8200
    ports:
      - "3001:3001"
    networks:
      - chatop-network

volumes:
  mysql_data:

networks: # Réseau à utiliser
  chatop-network: # Nom du réseau
    driver: bridge # Type de driver servant à créer le réseau
