services:
  mysql:
    image: mysql:8
    container_name: chatop-mysql
    restart: always
    environment:
      MYSQL_DATABASE: chatop
      MYSQL_USER: chatopuser
      MYSQL_PASSWORD: chatoppass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  mysql_data:
